<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ZSnaper.Installer.VisualQa</AssemblyName>
    <NoWarn>$(NoWarn);CS9057</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.1" />
    <ProjectReference Include="..\..\src\ZSnaper.FullInstaller\ZSnaper.FullInstaller.csproj" />
  </ItemGroup>
</Project>
