<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ZSnaper.Plugin.Abstractions</AssemblyName>
    <RootNamespace>ZSnaper.Plugins</RootNamespace>
    <Version>1.0.0</Version>
    <InformationalVersion>1.0.0</InformationalVersion>
  </PropertyGroup>

</Project>
