<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AssemblyName>ZSnaper.Installer.Core</AssemblyName>
    <RootNamespace>ZSnaper.Installer.Core</RootNamespace>
  </PropertyGroup>

</Project>
